apiVersion: v2
name: recipes
description: A Cloud Native Recipe Book
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 10.3.0