version: "3.7"
name: recipes
services:
  mongodb:
    image: bitnami/mongodb:4.4
    environment:
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=recipes
    volumes:
      - mongodb:/bitnami/mongodb 
      
    ports: 
      - '27017:27017'
  frontend:
    build: frontend
    ports:
      - 8080:8080
  api:
    build: api
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=recipes
    ports:
      - 8080:8080

volumes:
  mongodb:
    driver_opts:
      size: 1Gi
    
endpoints:
  - path: /api
    service: api
    port: 8080
  - path: /
    service: frontend
    port: 8080
  